export enum RoomError {
  NOT_FOUND = 'ROOM_NOT_FOUND',
  ALREADY_EXISTS = 'ROOM_ALREADY_EXISTS',
  FULL = 'ROOM_FULL',
  PRIVATE = 'ROOM_PRIVATE',
  NOT_OWNER = 'ROOM_NOT_OWNER',
  NOT_JOINED = 'ROOM_NOT_JOINED',
  JOINED = 'ROOM_JOINED',
  NOT_STARTED = 'ROOM_NOT_STARTED',
  STARTED = 'ROOM_STARTED',
  NOT_ENOUGH_PLAYERS = 'ROO_NOT_ENOUGH_PLAYERS'
}
