version: "3"

services:
  transcendence-front:
    container_name: transcendence-front
    image: transcendence-front
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 5173:5173
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npx vite --host
